"""
HandoffPackage - Multi-Model Agent Handoff State Machine
Manages the state transition between Claude 4.6 (Thinking) and Gemma 4 (Execution).
"""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from datetime import datetime, timedelta
from enum import Enum
import uuid
import json
import hashlib


class HandoffStatus(Enum):
    """Handoff state machine states."""
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    WORKING = "WORKING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    REJECTED = "REJECTED"


class AgentType(Enum):
    """Agent types."""
    CLAUDE_46 = "claude-4.6"
    GEMMA_4 = "gemma-4"


@dataclass
class TaskDefinition:
    """Task definition for handoff."""
    id: str
    type: str  # "trading", "analysis", "risk_check", etc.
    priority: str  # "low", "medium", "high", "critical"
    description: str
    context: Dict[str, Any]
    requirements: List[str] = field(default_factory=list)
    constraints: Dict[str, Any] = field(default_factory=dict)
    timeout_seconds: int = 300


@dataclass
class DeterministicPlan:
    """Deterministic plan generated by Claude 4.6."""
    id: str
    task_id: str
    steps: List[Dict[str, Any]]
    expected_outcome: Dict[str, Any]
    dependencies: List[Dict[str, str]] = field(default_factory=list)
    rollback_plan: Optional[Dict[str, Any]] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def to_hash(self) -> str:
        """Generate deterministic hash for plan validation."""
        plan_str = json.dumps({
            "steps": self.steps,
            "dependencies": self.dependencies,
            "expected_outcome": self.expected_outcome
        }, sort_keys=True)
        return hashlib.sha256(plan_str.encode()).hexdigest()


@dataclass
class CompressedContext:
    """Compressed context using TurboQuant."""
    embeddings: List[float]
    metadata: Dict[str, Any]
    original_size: int
    compressed_size: int
    compression_ratio: float
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class ExecutionResult:
    """Result from Gemma 4 execution."""
    id: str
    handoff_id: str
    status: str
    outputs: Dict[str, Any]
    execution_time_ms: float
    tokens_used: int
    reasoning_trace: List[Dict[str, Any]]
    errors: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class HandoffError:
    """Error information for failed handoffs."""
    code: str
    message: str
    agent: str
    step: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HandoffPackage:
    """Complete handoff package containing all state and data."""
    id: str
    task: TaskDefinition
    status: HandoffStatus
    source_agent: AgentType
    target_agent: AgentType
    
    # Plan and context
    plan: Optional[DeterministicPlan] = None
    context: Optional[CompressedContext] = None
    
    # Execution tracking
    execution: Optional[ExecutionResult] = None
    current_step: int = 0
    steps_completed: List[str] = field(default_factory=list)
    
    # Error handling
    errors: List[HandoffError] = field(default_factory=list)
    retry_count: int = 0
    max_retries: int = 3
    
    # Timing
    created_at: datetime = field(default_factory=datetime.utcnow)
    accepted_at: Optional[datetime] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    timeout_at: Optional[datetime] = None
    
    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate handoff package after creation."""
        if self.source_agent == self.target_agent:
            raise ValueError("Source and target agents must be different")
            
        if self.task.timeout_seconds and not self.timeout_at:
            self.timeout_at = self.created_at + datetime.timedelta(
                seconds=self.task.timeout_seconds
            )
    
    def can_transition_to(self, new_status: HandoffStatus) -> bool:
        """Check if state transition is valid."""
        valid_transitions = {
            HandoffStatus.PENDING: [HandoffStatus.ACCEPTED, HandoffStatus.REJECTED, HandoffStatus.TIMEOUT],
            HandoffStatus.ACCEPTED: [HandoffStatus.WORKING, HandoffStatus.FAILED, HandoffStatus.TIMEOUT],
            HandoffStatus.WORKING: [HandoffStatus.COMPLETE, HandoffStatus.FAILED, HandoffStatus.TIMEOUT],
            HandoffStatus.COMPLETE: [],  # Terminal state
            HandoffStatus.FAILED: [],     # Terminal state
            HandoffStatus.TIMEOUT: [],    # Terminal state
            HandoffStatus.REJECTED: []    # Terminal state
        }
        
        return new_status in valid_transitions.get(self.status, [])
    
    def transition_to(self, new_status: HandoffStatus, error: Optional[HandoffError] = None):
        """Transition to new state with validation."""
        if not self.can_transition_to(new_status):
            raise ValueError(f"Invalid transition from {self.status} to {new_status}")
        
        old_status = self.status
        self.status = new_status
        
        # Update timestamps
        now = datetime.utcnow()
        if new_status == HandoffStatus.ACCEPTED:
            self.accepted_at = now
        elif new_status == HandoffStatus.WORKING:
            self.started_at = now
        elif new_status in [HandoffStatus.COMPLETE, HandoffStatus.FAILED, HandoffStatus.TIMEOUT]:
            self.completed_at = now
        
        # Log error if provided
        if error:
            self.errors.append(error)
        
        # Log state transition
        self._log_transition(old_status, new_status, error)
    
    def _log_transition(self, old_status: HandoffStatus, new_status: HandoffStatus, error: Optional[HandoffError]):
        """Log state transition for audit."""
        transition = {
            "handoff_id": self.id,
            "from": old_status.value,
            "to": new_status.value,
            "timestamp": datetime.utcnow().isoformat(),
            "error": error.code if error else None
        }
        
        # Store in metadata for audit
        if "transitions" not in self.metadata:
            self.metadata["transitions"] = []
        self.metadata["transitions"].append(transition)
    
    def is_timeout(self) -> bool:
        """Check if handoff has timed out."""
        if not self.timeout_at:
            return False
        return datetime.utcnow() > self.timeout_at
    
    def can_retry(self) -> bool:
        """Check if handoff can be retried."""
        return self.retry_count < self.max_retries and self.status in [HandoffStatus.FAILED]
    
    def increment_retry(self):
        """Increment retry count."""
        self.retry_count += 1
        self.status = HandoffStatus.PENDING
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "task": {
                "id": self.task.id,
                "type": self.task.type,
                "priority": self.task.priority,
                "description": self.task.description
            },
            "status": self.status.value,
            "source_agent": self.source_agent.value,
            "target_agent": self.target_agent.value,
            "plan": {
                "id": self.plan.id,
                "hash": self.plan.to_hash() if self.plan else None,
                "steps": len(self.plan.steps) if self.plan else 0
            } if self.plan else None,
            "execution": {
                "id": self.execution.id,
                "status": self.execution.status,
                "time_ms": self.execution.execution_time_ms
            } if self.execution else None,
            "current_step": self.current_step,
            "errors": len(self.errors),
            "retry_count": self.retry_count,
            "created_at": self.created_at.isoformat(),
            "accepted_at": self.accepted_at.isoformat() if self.accepted_at else None,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None
        }
    
    def validate_reasoning_lock_in(self) -> bool:
        """Validate no reasoning lock-in occurred."""
        if not self.plan or not self.execution:
            return True
        
        # Check if execution followed the plan exactly
        plan_steps = set(step.get("id") for step in self.plan.steps)
        executed_steps = set(step.get("step_id") for step in self.execution.reasoning_trace)
        
        # All executed steps should be in the plan
        extra_steps = executed_steps - plan_steps
        if extra_steps:
            self.errors.append(HandoffError(
                code="REASONING_LOCK_IN",
                message=f"Execution included steps not in plan: {extra_steps}",
                agent=self.target_agent.value,
                step="validation",
                details={"extra_steps": list(extra_steps)}
            ))
            return False
        
        return True
